# Generated by Django 4.0.3 on 2022-03-06 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClientProfile', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GallonPrice',
            new_name='ClientProfile',
        ),
    ]
