# Generated by Django 4.0.3 on 2022-03-06 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClientProfile', '0002_rename_gallonprice_clientprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientprofile',
            old_name='price',
            new_name='description',
        ),
    ]
