# Generated by Django 4.0.3 on 2022-03-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientProfile', '0003_rename_price_clientprofile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='price',
            field=models.TextField(default='Test'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='summary',
            field=models.TextField(default='Test'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='title',
            field=models.TextField(default='Test'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='description',
            field=models.TextField(default='Test'),
        ),
    ]
