# Generated by Django 4.0.3 on 2022-03-06 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClientProfile', '0004_clientprofile_price_clientprofile_summary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientprofile',
            old_name='summary',
            new_name='client_name',
        ),
        migrations.RenameField(
            model_name='clientprofile',
            old_name='title',
            new_name='history',
        ),
    ]
