# Generated by Django 4.0.3 on 2022-03-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientProfile', '0006_remove_clientprofile_client_name_clientprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='history',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10000),
        ),
    ]
