# Generated by Django 4.0.3 on 2022-03-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientProfile', '0011_alter_clientprofile_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='history',
            field=models.TextField(blank=True),
        ),
    ]
