# Generated by Django 4.0.3 on 2022-03-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientProfile', '0012_alter_clientprofile_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
